config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :create ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name,  presence: true
  validates :address, presence: true
  validates :category,
    presence: true,
    inclusion: { in: [
      'chinese',
      'italian',
      'japanese',
      'french',
      'belgian'
    ], allow_nil: false }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content,  presence: true
  validates :rating,
    numericality: { only_integer: true },
    inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }
  validates :restaurant_id,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(resto_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(resto_params)
  end

  def destroy
    @restaurant.destroy
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def resto_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private
  def review_params
    params[:rating] = params[:rating].to_i
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.full_error :token %>
  <%= f.input :name %>
  <%= f.input :address, as: :text %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian'] %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
  <%= f.full_error :token %>
<% end %>

<%= link_to "back to list", restaurants_path %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="container">

    <h1 class="text-center">My list of restaurants</h1>
    <div class="text-center">
      <%= link_to 'create new restaurant', new_restaurant_path, class: "btn btn-info" %>
    </div>



  <div class="row">
    <% @restaurants.each_with_index do |restaurant, i| %>
    <div class="col-xs-12 col-md-6 col-lg-4 text-center">
        <div class="card">
          <div>
            <%= image_tag "#{i + 1}", class: "card-image" %>
          </div>
          <div class="card-title">
            <%= link_to restaurant.name, restaurant_path(restaurant), class: "card-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1 >New restaurant</h1>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<div>
  <h1><%= @restaurant.name %></h1>
</div>

<div>
  <%= link_to "Edit restaurant details", edit_restaurant_path, class: "btn btn-primary" %>
  <p>Address: <%= t(@restaurant.address) %></p>
  <p>Phone: <%= t(@restaurant.phone_number) %></p>
  <p>Category: <%= t(@restaurant.category) %></p>
</div>

<div>
<h2>Ratings</h2>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= "#{review.content} #{'*' * review.rating} " %></li>
  <% end %>
</ul>
</div>

<div>
<%= "Add new review for #{@restaurant.name}" %>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.full_error :token %>
  <%= f.input :content, as: :text %>
  <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
  <%= f.full_error :token %>
<% end %>

</div>
<%= link_to "back to list", restaurants_path %>